name: Bug report
description: Report a reproducible defect in Cortex behavior
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please include concrete reproduction steps and verification output.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line description of the bug
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Exact commands and files used
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Include Cortex version, Python version, OS, and relevant config snippets
      placeholder: |
        cortex==...
        python==...
        os==...
    validations:
      required: true
  - type: textarea
    id: checks
    attributes:
      label: Validation output
      description: Paste `cortex check --root <project>` and failing test/lint output
    validations:
      required: true
